FROM php:8.2-apache

COPY index.php /var/www/html/index.php
COPY flag.txt /var/www/html/PomegranateJuiceFactory/flag.txt
# Set permissions
RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html

CMD ["apache2-foreground"]
